### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by mat9819** [castore-dev/castore#134]
Hi Castore team !

Thank you for your great work on the library.

**Is your feature request related to a problem? Please describe.**
I am looking for a multitenancy event sourcing library. 
How would you approach this in Castore ?

**Describe the solution you'd like**
I am not an expert of event sourcing but I would like to add to all events a tenantId property and modify the dynamodb event-storage-adapter in order to partition data by tenants. 

**Describe alternatives you've considered**
One alternative is to create everything from scratch but I'd rather use your library. 

Thank you very much for your help !

**Comment by ThomasAribart** [comment]
Hi @mat9819 and thanks for your interest !

I think that's an interesting feature so I'll add it to the roadmap. We could create a `TenantizedEventStore` that follows the `EventStore` interface while adding a `tenantId` argument for each method. And maybe modify the event storage adapter to expose a `listTenants` method ?

That's a lot of work and you're the only person having this need. We're a small team so we won't prioritize it for the next 6 months I think (we have more frequently asked subjects like snapshots and read models).

Two solutions that could do the trick right now:

1: Keep one event store and prefix your aggregate ids by a tenant id:

```ts
await eventStore.getAggregate(`${tenantId}#{aggregateId}`)
```

It will work but will degrade the performance of the `listAggregateIds` method for one tenant as you would have to list all the aggregate ids and filter manually the ones that begin by your `tenantId`. It should an acceptable tradeoff as `listAggregateIds` is mainly there for maintenance / migration jobs.

2: Suffix your event store by a tenant id

```ts
const tenantEventStore = new EventStore({
  eventStoreId: `POKEMONS#${tenantId}`
  ...
})
```

This solves the problem of the `listAggregateIds` but means that:
- You need a custom method outside of Castore to save/retrieve all your `tenantIds`
- In your code, you will construct an event store class each time you want to interact with one of your tenant. So it will impact your backend performances.

I would rather go with the first solution.

Hope it helped ! Thanks for the issue !

**Comment by ThomasAribart** [comment]
@mat9819  there's actually a 3rd solution which is to create a new event store called `tenant` and join your data with message groups. See this page for an example: https://castore-dev.github.io/castore/docs/event-sourcing/joining-data/

**Comment by ThomasAribart** [comment]
Closing this as there's no plan to implement this in the near future.
