### ISSUE TITLE
Some qs.

### ISSUE THREAD

**Issue by cloudcompute** [castore-dev/castore#150]
The project looks great.

Is anyone using it in production?

Handling backpressure will be taken care by a message bus adapter, am I right?

What exactly is the purpose of updating an aggregate in memory every time an event is saved in the store?

Thank you

**Comment by ThomasAribart** [comment]
Hello @cloudcompute 

Yes, it is in use in many projects in production.

What do you mean by backpressure ? You mean reacting to events ?

An aggregate is a series of events passed through a reducer function. If you save a new event in the store, it is necessarily updated. However, until we provide support for snapshots, they are not saved in any database. So I guess I don't really understand your question.

We have a new docs website, feel free to check it out, maybe it will answer some of your questions: https://castore-dev.github.io/castore/

**Comment by cloudcompute** [comment]
@ThomasAribart 

Ty for the response. By backpressure, I meant this:
https://singhwarrior.github.io/Event-Based-Application-Implementing-Back-Pressure/
