### ISSUE TITLE
Big Fan. SST Example Repo

### ISSUE THREAD

**Issue by ghardin1314** [castore-dev/castore#153]
First off, big fan of the effort being made here. Our team has been using event sourcing for the last year or so and love the pattern. We are planning to migrate our next version to serverless and this looks like the right library to help us do that.

As part of the exploration process, I re-implemented your demo using the SST framework which you can see [here](https://github.com/ghardin1314/sst-castore) (if you want to show as a reference for new users):

Also took it a step further and implemented dynamo table event streaming like depicted in your [article](https://dev.to/slsbytheodo/serverless-event-sourcing-with-aws-state-of-the-art-data-synchronization-4mog) (which is how I found this library)

Anyway, would love to contribute as we start adopting this. Sounds like there is big plans for new features coming up so let me know if there is a place to start. I think I will try and implement `ZodCommand` this weekend as that would be useful for us and seems to be missing at the moment and should be easy

**Comment by ThomasAribart** [comment]
Hey @ghardin1314 ! Thanks for the love, it's really appreciated 🤗

Any contribution is welcome :) The more the merrier!

We have big plans for Castore, our roadmap for the next 6 months is mainly going to be on supporting snapshots and read models, as well as developing an admin (based on the visualizer).

However, we already have some ideas on how to implement them and it's not the easiest subjects to start with. Easier subjects that come to mind:
- Supporting more validation libraries (`ZodCommand` is a very good start indeed)
- Supporting more storage/messaging solutions (but I guess you're good with the current adapters for now)
- Improving the visualizer, which is very basic for the moment (see an example in the [new docs](https://castore-dev.github.io/castore/visualizer/)). For instance, you could work on making it compatible with Zod. Then, and anticipating that it will become an admin, a lot of features miss like aggregate filters based on date, nice notifications when a event is pushed or an error happens, a new tab displaying the graph of the architecture etc. 

Many thanks! Can't wait to read your PR :)

PS: It's quite hidden but don't hesitate to read [this issue](https://github.com/castore-dev/castore/issues/49) about read models, contains a lot of good infos :)

**Comment by ghardin1314** [comment]
Nice, will look into some improvements for the visualizer when I have free time. 

Also I have a pretty good idea for how we will implement read models and replays based on your writings and previous efforts. Looking forward to the snapshotting features though!

**Comment by ThomasAribart** [comment]
@ghardin1314 Snapshotting is next on the list :)

Thanks for the PR, `command-zod` is now available since v2.1.0 ! https://www.npmjs.com/package/@castore/command-zod
