### ISSUE TITLE
Curious about the Messagebus / Queue plan

### ISSUE THREAD

**Issue by KeKs0r** [castore-dev/castore#48]
**Is your feature request related to a problem? Please describe.**

I would be curious what the Ideas  around MessageBus / Queues are.
I did a dirty hack for my project to add an event emitter to the `EventStore` in order to listen to events and then put them on a queue.

But I think having an abstract interface like for the `eventStoreStorage` makes probably more sense. So curious on what the ideas around that are, and whether I can help.

**Describe alternatives you've considered**

```typescript
import Emittery from 'emittery'
import type {
    $Contravariant,
    Aggregate,
    EventDetail,
    EventType,
    EventTypesDetails,
    Reducer,
} from '@castore/core'
import { EventStore as BaseEventStore } from '@castore/core'

export class EventStore<
    I extends string = string,
    E extends EventType[] = EventType[],
    D extends EventDetail = EventTypesDetails<E>,
    // cf https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-rc/#optional-variance-annotations-for-type-parameters
    // EventStore is contravariant on its fns args: We have to type them as "any" so that EventStore implementations still extends the EventStore type
    $D extends EventDetail = $Contravariant<D, EventDetail>,
    R extends Reducer<Aggregate, $D> = Reducer<Aggregate, $D>,
    A extends Aggregate = ReturnType<R>,
    $A extends Aggregate = $Contravariant<A, Aggregate>
> extends BaseEventStore<I, E, D, $D, R, A, $A> {
    emitter: Emittery
    constructor(...args: ConstructorParameters<typeof BaseEventStore<I, E, D, $D, R, A, $A>>) {
        super(...args)
        this.emitter = new Emittery()

        const originalPushEvent = this.pushEvent
        this.pushEvent = async (event: $D) => {
            await originalPushEvent(event)
            await this.emit(event)
        }
    }

    on<EventType extends E[number]>(
        eventName: EventType['type'],
        listener: (event: EventDetail<EventType>) => Promise<void>
    ) {
        this.emitter.on(eventName, listener)
        return () => this.emitter.off(eventName, listener)
    }

    emit<EventType extends E[number]>(event: EventDetail<EventType>) {
        return this.emitter.emit(event.type, event)
    }
}

```

**Comment by ThomasAribart** [comment]
Hello @KeKs0r !

Message queues and buses are now a thing in Castore 🥳 With adapters for SQS, Event-bridge and in-memory solutions (I used `fastq` for queues and native `EventEmitters` for buses). Check the docs: https://github.com/castore-dev/castore#--event-driven-architecture

Can't wait to hear your feedbacks :)

I think it would make sense for event stores to be seamlessly connected to notification message buses & queues 🤔 Actually it could be done through the adapter:

```ts
const myEventStore = new EventStore({
  eventStorageAdapter: withMessageQueue(new InMemoryEventStorageAdapter(...), new NotificationMessageQueue(...))
})
```

Or we could also provide "destination" attributes:

```ts
const myEventStore = new EventStore({
  eventStorageAdapter: ...,
  destinationMessageQueue: new NotificationMessageQueue(...)
})
```

What do you think?

**Comment by ThomasAribart** [comment]
Hi @KeKs0r !

Just published a new version with a new class: [`ConnectedEventStores`](https://github.com/castore-dev/castore#--connectedeventstore). I hope that this, along with the `InMemoryMessageBusAdapter`, will match your needs!

Closing this issue right now :)
