### ISSUE TITLE
DynamoDB Single Table Eventstore

### ISSUE THREAD

**Issue by nirweiner2** [castore-dev/castore#93]
One option for configuring the DynamoDB Event Store is to use a SingleTable setup. This approach could reduce the amount of repetitive code required to create a new table for each aggregate. Furthermore, it could enhance performance by enabling multiple aggregates to be fetched in a single call at a later stage, potentially also leading to cost savings.

**Comment by ThomasAribart** [comment]
@nirweiner2 Thanks for the suggestion :)

Indeed, I was thinking about adding the event store id as a prefix for aggregate partitions to the `DynamoDBEventStorageAdapter` so one table could serve for several event stores. Would that be a good solution for you ?

**Comment by nirweiner2** [comment]
You mean, the aggregate type. Correct?
If that's what you mean then I think this is the right way to do it. :)

**Comment by ThomasAribart** [comment]
Yes, so if you're event store id is called `POKEMONS`, you would have the following event details in DynamoDB:

```ts
{
  aggregateId: "POKEMONS#01234567" // <= Pokemon id prefixed by POKEMONS
  version: 10
  type: "POKEMON_CATCHED"
  ...
}
```

**Comment by nirweiner2** [comment]
Exactly
